
[functions.send-digest-push]
enabled = true
verify_jwt = false
import_map = "./functions/send-digest-push/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-digest-push/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-digest-push/*.html" ]

[functions.auth-rate-limit]
enabled = true
verify_jwt = false
import_map = "./functions/auth-rate-limit/deno.json"
entrypoint = "./functions/auth-rate-limit/index.ts"
